SDK update to 1.3.1, selectors update, added proxy usage, maxItems to…
vbartonicek/topuniversities-scraper pull request #13
Opened 2021-07-29 14:48 UTC by OlehVeselov92

… the input, better logging, new fields in the output

2021-07-29 15:46 UTC, pocesar requested changes
minor changes

2021-07-29 15:46 UTC, pocesar commented on src/main.js
> +                data = await page.$$eval('body', detailPageFunction);
this is returning an array, the output is being `{ "0": {} }`. you can split the details when doing pushData (below)

2021-07-29 15:46 UTC, pocesar commented on src/main.js
> +                await Apify.pushData(data);
```js
// either one per row
for (const data of await page.$$eval('body', detailPageFunction)) {
   await Apify.pushData({ ...data, detail_page: url });
}
// or passed as an array to the output, `data` will be an array
data = await page.$$eval('body', detailPageFunction);
await Apify.pushData({ data, detail_page: url });
```

2021-07-29 15:46 UTC, pocesar commented on src/scrapers.js
> +            QS_World_University_Rankingnk: $university.querySelector('._univ-rank')
`Rankingnk` typo

2021-07-29 15:46 UTC, pocesar commented on src/scrapers.js
> +            locationsResult.push(locationNode.textContent.trim());
this is having a "\n" inside, maybe split between address/country? there are two spans inside. the array can be like 

```js
locations.forEach((locationNode) => {
  const [location, country] = locationNode.querySelectorAll('span');
  locationsResult.push({
    country: country?.textContent?.trim(),
    mapLink: locationNode.href,
    location: location?.textContent?.trim().replace(/,$/, ''),
  });
});
```

2021-07-30 14:12 UTC, vbartonicek approved these changes
Thanks for fixing that, @OlehVeselov92! I owe you a beer! :-)

2021-08-03 03:43 UTC, pocesar approved these changes

2021-08-03 03:43 UTC, merged